SELECT *,

      CASE 
        WHEN STOCK_VALUE = 0 THEN 0 
          
        WHEN STOCK_VALUE >0 AND AVG_SALES_IN_STOCK_42_DAYS = 0 AND AVG_SALES_IN_STOCK_365_DAYS > 0 THEN STOCK_VALUE 
        
        ELSE 0 
        END     AS SUM_OF_NON_MOVING_42_DAYS,


      CASE 

        WHEN STOCK_VALUE = 0 THEN 0 
        
        WHEN STOCK_VALUE >0 AND AVG_SALES_IN_STOCK_42_DAYS >0 AND  ESTIMATED_STOCK_DAYS < 31   THEN STOCK_VALUE 

        WHEN STOCK_VALUE >0 AND AVG_SALES_IN_STOCK_42_DAYS >0 AND  ESTIMATED_STOCK_DAYS > 30   THEN (30 * STOCK_VALUE)  / ESTIMATED_STOCK_DAYS 
        
        ELSE 0 
        END  AS SUM_OF_0_30_DGN,


      CASE 
        WHEN STOCK_VALUE = 0 THEN 0 

        WHEN STOCK_VALUE >0 AND AVG_SALES_IN_STOCK_42_DAYS >0 AND  (ESTIMATED_STOCK_DAYS > 30 AND ESTIMATED_STOCK_DAYS < 91)   
        
              THEN ((ESTIMATED_STOCK_DAYS-30) * STOCK_VALUE)  / ESTIMATED_STOCK_DAYS 

        WHEN STOCK_VALUE >0 AND (AVG_SALES_IN_STOCK_42_DAYS >0 AND  ESTIMATED_STOCK_DAYS > 90 )   
              THEN ((90-30) * STOCK_VALUE)  / ESTIMATED_STOCK_DAYS 
              
        ELSE 0 
        END  AS SUM_OF_31_90_DGN,


   

      CASE 
        WHEN STOCK_VALUE = 0 THEN 0 
        WHEN STOCK_VALUE >0 AND AVG_SALES_IN_STOCK_42_DAYS >0 AND  (ESTIMATED_STOCK_DAYS > 90 AND ESTIMATED_STOCK_DAYS < 181)   THEN ((ESTIMATED_STOCK_DAYS-90) * STOCK_VALUE)  / ESTIMATED_STOCK_DAYS 
        WHEN STOCK_VALUE >0 AND (AVG_SALES_IN_STOCK_42_DAYS >0 AND  ESTIMATED_STOCK_DAYS > 180 )   THEN ((180-90) * STOCK_VALUE)  / ESTIMATED_STOCK_DAYS 
        ELSE 0 
        END  AS SUM_OF_91_180_DGN,


      CASE 
        WHEN STOCK_VALUE = 0 THEN 0 
        WHEN STOCK_VALUE >0 AND AVG_SALES_IN_STOCK_42_DAYS >0 AND  (ESTIMATED_STOCK_DAYS > 180 AND ESTIMATED_STOCK_DAYS < 366)    THEN ((ESTIMATED_STOCK_DAYS-180) * STOCK_VALUE)  / ESTIMATED_STOCK_DAYS 
        WHEN STOCK_VALUE >0 AND (AVG_SALES_IN_STOCK_42_DAYS >0 AND  ESTIMATED_STOCK_DAYS > 365)  THEN ((365-180) * STOCK_VALUE)  / ESTIMATED_STOCK_DAYS 
        ELSE 0
        END  AS SUM_OF_180_365_DGN,



      CASE 
        WHEN STOCK_VALUE = 0 THEN 0 
        WHEN STOCK_VALUE >0 AND (AVG_SALES_IN_STOCK_42_DAYS >0 AND ESTIMATED_STOCK_DAYS > 365)  THEN ((ESTIMATED_STOCK_DAYS-365) * STOCK_VALUE)  / ESTIMATED_STOCK_DAYS 
        ELSE 0 
        END AS MORE_THAN_365_DGN,

      CASE 
        WHEN STOCK_VALUE >0 AND (AVG_SALES_IN_STOCK_42_DAYS = 0 AND AVG_SALES_IN_STOCK_365_DAYS = 0) THEN STOCK_VALUE 
        ELSE 0 
        END  AS SUM_OF_NON_MOVING_365_DAYS
      

FROM `hbl-online.purchase_queries.stock_health_Trend`